# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='image',
            field=models.FileField(default='1', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
